version: '3.8'

services:
  storage-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage-service
    ports:
      - "3020:3020"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/src/app/uploads
